apiVersion: apps/v1
kind: Deployment
metadata:
  name: zora-fe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zora-fe
  template:
    metadata:
      labels:
        app: zora-fe
    spec:
      containers:
        - name: zora-fe
          image: 192.168.10.222:5001/zora-fe:BUILD_TAG_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: zora-fe-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: zora-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081  # change if conflicts with existing NodePorts
